apiVersion: v1
kind: Namespace
metadata:
  name: pinniped-supervisor
---
apiVersion: v1
kind: Secret
metadata:
  name: supervisor-serving-cert
  namespace: pinniped-supervisor
type: kubernetes.io/tls
stringData:
  tls.crt: |
    %MGMT_CLUSTER_TLS_CERT_WITH_INTERMEDIATE_CA_PEM%
  tls.key: |
    %MGMT_CLUSTER_TLS_KEY_PEM%
  ca.crt: |
    %RNCC_ROOT_CA_PEM%
---
apiVersion: v1
kind: Secret
type: tkg.tanzu.vmware.com/addon
metadata:
  annotations:
    tkg.tanzu.vmware.com/addon-type: authentication/pinniped
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    tkg.tanzu.vmware.com/addon-name: pinniped
    tkg.tanzu.vmware.com/cluster-name: %CLUSTER_NAME%
  name: %CLUSTER_NAME%-pinniped-addon
  namespace: tkg-system
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    infrastructure_provider: vsphere
    tkg_cluster_role: management
    custom_cluster_issuer: ""
    custom_tls_secret: "supervisor-serving-cert"
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
    identity_management_type: ldap
    pinniped:
      cert_duration: 2160h
      cert_renew_before: 360h
      supervisor_svc_endpoint: https://%MGMT_CLUSTER_FQDN%:31234
      supervisor_ca_bundle_data: "%RNCC_ROOT_CA_BASE64%"
      supervisor_svc_external_ip: 0.0.0.0
      supervisor_svc_external_dns: https://%MGMT_CLUSTER_FQDN%:31234
      upstream_oidc_client_id: ""
      upstream_oidc_client_secret: ""
      upstream_oidc_issuer_url: https://0.0.0.0:30167
      upstream_oidc_tls_ca_data: ca_bundle_data_of_dex_svc
      upstream_oidc_additional_scopes:
      - email
      - profile
      - groups
      upstream_oidc_claims:
        username: name
        groups: groups
      supervisor:
        service:
          name: pinniped-supervisor
          type: NodePort
    dex:
      app: dex
      create_namespace: true
      namespace: tanzu-system-auth
      organization: vmware
      commonname: tkg-dex
      config:
        connector: ldap
        frontend:
          theme: tkg
        web:
          https: 0.0.0.0:5556
          tlsCert: /etc/dex/tls/tls.crt
          tlsKey: /etc/dex/tls/tls.key
        expiry:
          signingKeys: 90m
          idTokens: 5m
          authRequests: 90m
          deviceRequests: 5m
        logger:
          level: info
          format: json
        staticClients:
        - id: pinniped
          redirectURIs:
          - https://0.0.0.0/callback
          name: pinniped
          secret: dummyvalue
        ldap:
          host: sv-ad01-rnoc-s.oss.vf.rogers.com
          insecureNoSSL: false
          startTLS: null
          rootCA: null
          rootCAData: null
          bindDN: CN=rnccadmin,OU=Service Accounts,DC=oss,DC=vf,DC=rogers,DC=com
          BIND_PW_ENV_VAR: %LDAP_PASSWORD%
          usernamePrompt: OSS-AD Username
          insecureSkipVerify: false
          userSearch:
            baseDN: DC=oss,DC=vf,DC=rogers,DC=com
            filter: (objectClass=user)
            username: sAMAccountName
            idAttr: sAMAccountName
            emailAttr: userPrincipalName
            nameAttr: sAMAccountName
            scope: sub
          groupSearch:
            baseDN: DC=oss,DC=vf,DC=rogers,DC=com
            filter: (objectClass=group)
            nameAttr: cn
            scope: sub
            userMatchers:
            - userAttr: DN
              groupAttr: "member:1.2.840.113556.1.4.1941:"
        oauth2:
          skipApprovalScreen: true
          responseTypes:
          - code
        storage:
          type: kubernetes
          config:
            inCluster: true
        enablePasswordDB: false
      service:
        name: dexsvc
        type: NodePort
      deployment:
        replicas: 1
      certificate:
        duration: 2160h
        renewBefore: 360h
      dns:
        vsphere:
          dnsNames:
          - tkg-dex.com
          ipAddresses:
          - 0.0.0.0
        aws:
          dnsNames:
          - tkg-dex.com
          DEX_SVC_LB_HOSTNAME: example.com
        azure:
          dnsNames:
          - tkg-dex.com
          DEX_SVC_LB_HOSTNAME: dex.example.com
