# RNCC AKO 2.1.2 Helm Values Template
#
# Replace all instances of the following variables with the correct value:
#
# ${HARBOR_FQDN} - The FQDN of the Harbor registry
# ${NSX_T1_PATH} - The path of the NSX T1 router
# ${AVI_VIP_NETWORK_NAME} - The network VIP network defined in AVI Controller
# ${CLUSTER_NAME} - The K8s cluster name as defined in TCA
# ${SRV_DOMAIN_NAME} - The domain name of the SRV zone
# ${AVI_CONTROLLER_FQDN} - The FQDN of the AVI controller
# ${AVI_CONTROLLER_VERSION} - The version of the AVI controller
# ${AVI_CLOUD_NAME} - The cloud name defined in AVI controller
# ${AVI_SA_USERNAME} - The username of the AKO service account
# ${AVI_SA_PASSWORD} - The password of the AKO service account
#
featureGates:
  GatewayAPI: false
  EnablePrometheus: true
replicaCount: 1
image:
  repository: ${HARBOR_FQDN}/library/ako
  pullPolicy: IfNotPresent
  pullSecrets: []
GatewayAPI:
  image:
    repository: ${HARBOR_FQDN}/library/ako-gateway-api
    pullPolicy: IfNotPresent
AKOSettings:
  primaryInstance: true
  enableEvents: "true"
  logLevel: "WARN"
  fullSyncFrequency: "1800"
  apiServerPort: 8080
  deleteConfig: "false"
  disableStaticRouteSync: "false"
  clusterName: "${CLUSTER_NAME}"
  cniPlugin: "antrea"
  enableEVH: false
  layer7Only: false
  namespaceSelector:
    labelKey: ""
    labelValue: ""
  servicesAPI: false
  vipPerNamespace: "false"
  istioEnabled: false
  blockedNamespaceList: []
  ipFamily: ""
  useDefaultSecretsOnly: "false"
  vpcMode: false
NetworkSettings:
  nodeNetworkList: []
  enableRHI: false
  nsxtT1LR: "${NSX_T1_PATH}"
  bgpPeerLabels: []
  vipNetworkList:
  - networkName: "${AVI_VIP_NETWORK_NAME}"
    cidr: 0.0.0.0/0
  defaultDomain: "${CLUSTER_NAME}.${SRV_DOMAIN_NAME}"
L7Settings:
  defaultIngController: "false"
  noPGForSNI: false
  serviceType: ClusterIP
  shardVSSize: "LARGE"
  passthroughShardSize: "SMALL"
  enableMCI: "false"
  fqdnReusePolicy: "InterNamespaceAllowed"
L4Settings:
  defaultLBController: "true"
  defaultDomain: "${CLUSTER_NAME}.${SRV_DOMAIN_NAME}"
  autoFQDN: "default"
ControllerSettings:
  serviceEngineGroupName: "${CLUSTER_NAME}"
  controllerVersion: "${AVI_CONTROLLER_VERSION}"
  cloudName: "${AVI_CLOUD_NAME}"
  controllerHost: "${AVI_CONTROLLER_FQDN}"
  tenantName: "admin"
  vrfName: ""
  dedicatedTenantMode: false
nodePortSelector:
  key: ""
  value: ""
resources:
  limits:
    cpu: 350m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 300Mi
securityContext: {}
podSecurityContext: {}
rbac:
  pspEnable: false
avicredentials:
  username: "${AVI_SA_USERNAME}"
  password: "${AVI_SA_PASSWORD}"
  authtoken:
  certificateAuthorityData: |
    ${ROOT_CA_PEM}
persistentVolumeClaim: ""
mountPath: "/log"
logFile: "avi.log"
akoGatewayLogFile: "avi-gw.log"
ako-crd-operator:
  enabled: true
  controllerManager:
    container:
      image:
        repository: ${HARBOR_FQDN}/library/ako-crd-operator
        imagePullPolicy: IfNotPresent
        pullSecrets: []
      resources:
        limits:
          cpu: 256m
          memory: 128Mi
        requests:
          cpu: 128m
          memory: 64Mi
      mountPath: "/log"
      logFile: "ako-crd-operator.log"
    persistentVolumeClaim: ""